version: "3.7"
services:
  fastapi:
    image: your-fastapi-image
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=your_db_host
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
      - GROQ_API_KEY=your_groq_api_key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`your-api-domain.com`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
